version: '3.8'

services:
  # ----------------------------------------------------------------------------
  # BANCO DE DADOS: POSTGRESQL 16+
  # Execução: docker compose --profile postgres up -d
  # ----------------------------------------------------------------------------
  postgres_db:
    build: ./databases/postgres
    container_name: protheus_postgres
    profiles:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD:-postgres_dev_pwd}
      - POSTGRES_DB=${POSTGRES_ROOT_USER:-postgres}
      - DB_PROTHEUS_NAME=${DB_NAME}
      - DB_PROTHEUS_USER=${DB_USER}
      - DB_PROTHEUS_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  # ----------------------------------------------------------------------------
  # BANCO DE DADOS: MS SQL SERVER 2022
  # Execução: docker compose --profile sqlserver up -d
  # ----------------------------------------------------------------------------
  sqlserver_db:
    build: ./databases/sqlserver
    container_name: protheus_sqlserver
    profiles:
      - sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - DB_PROTHEUS_NAME=${DB_NAME}
      - DB_PROTHEUS_USER=${DB_USER}
      - DB_PROTHEUS_PASSWORD=${DB_PASS}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  pg_data:
  sql_data: